Modify help message
minio/directpv pull request #484
Opened 2022-01-03 16:44 UTC by sinhaashish

2022-01-03 17:34 UTC, wlan0 commented on cmd/kubectl-directpv/kubectl-direct_csi.go
> +	if filepath.Base(os.Args[0]) == "kubectl-directpv" {
this checks for old binary name and shows the deprecation notice. The check should be for direct_csi, not directpv.

2022-01-03 18:53 UTC, harshavardhana requested changes

2022-01-03 18:53 UTC, harshavardhana commented on cmd/kubectl-directpv/kubectl-direct_csi.go
> +	if filepath.Base(os.Args[0]) == "kubectl-directpv" {
```suggestion
	if filepath.Base(os.Args[0]) == "kubectl-direct_csi" {
```

2022-01-03 19:10 UTC, wlan0 commented on cmd/kubectl-directpv/drives.go
> +	// drivesCmd.SetUsageTemplate("kubectl ashish")
delete

2022-01-04 03:16 UTC, sinhaashish commented
Not relevant anymore

2022-01-04 03:16 UTC, closed without merging