Cancel previous githubCI jobs when the PR is updated
minio/directpv pull request #494
Opened 2022-01-05 04:03 UTC by Praveenrajmani

2022-01-05 04:05 UTC, harshavardhana requested changes

2022-01-05 04:05 UTC, harshavardhana commented on .github/workflows/go.yml
> +      cancel-in-progress: true
generally should be at the top

```
# This ensures that previous jobs for the PR are canceled when the PR is
# updated.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true
```

refer here https://twitter.com/kubesploit/status/1477613591465394177

2022-01-05 06:47 UTC, harshavardhana approved these changes

2022-01-05 07:18 UTC, balamurugana requested changes

2022-01-05 07:18 UTC, balamurugana commented on .github/workflows/go.yml
> +  cancel-in-progress: true
Can you add this into all github workflows?

2022-01-05 12:09 UTC, balamurugana approved these changes

2022-01-06 04:34 UTC, wlan0 approved these changes

2022-01-06 04:34 UTC, merged