Add support for kubernetes v1.23
minio/directpv pull request #522
Opened 2022-01-31 10:52 UTC by Praveenrajmani

Fixes #507

2022-02-02 01:26 UTC, wlan0 commented on pkg/installer/installer.go
> +			return newV1Dot23(config), nil
Add a default that prints and still installs using the latest installer. 

```
Running on experimental version of kubernetes v1.xx. This version is not officially supported yet.
```

2022-02-02 01:26 UTC, wlan0 requested changes
Add test cases and add a default installer

2022-04-20 12:25 UTC, sinhaashish commented
Tested by building

2022-04-20 12:26 UTC, sinhaashish approved these changes

2022-04-20 15:03 UTC, wlan0 approved these changes

2022-04-20 15:03 UTC, merged