Configure XFS retry timeout to 60 seconds for EIO/ENOSPC errors
minio/directpv pull request #753
Opened 2023-04-12 03:07 UTC by balamurugana

2023-04-12 03:19 UTC, harshavardhana approved these changes

2023-04-12 03:20 UTC, harshavardhana commented on pkg/xfs/mount_linux.go
> +		return fmt.Errorf("unable to set EIO retry_timeout_seconds for device %v; %w", name, err)
Actually even 30s is more than enough @balamurugana

2023-04-12 03:22 UTC, harshavardhana commented
Oh btw @balamurugana rhel7 doesn't have these files.

2023-04-12 03:23 UTC, harshavardhana requested changes

2023-04-12 05:03 UTC, balamurugana commented
> Oh btw @balamurugana rhel7 doesn't have these files.
> 
> It's only on rhel8 and above..

@harshavardhana rhel 7 has the support
```sh
[root@master ~]# cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)

[root@master ~]# uname -a
Linux master 3.10.0-1160.88.1.el7.x86_64 #1 SMP Tue Mar 7 15:41:52 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

[root@master ~]# ls -1 /sys/fs/xfs/vdb/error/metadata/{EIO,ENOSPC}/retry_timeout_seconds
/sys/fs/xfs/vdb/error/metadata/EIO/retry_timeout_seconds
/sys/fs/xfs/vdb/error/metadata/ENOSPC/retry_timeout_seconds

[root@master ~]# cat /sys/fs/xfs/vdb/error/metadata/EIO/retry_timeout_seconds /sys/fs/xfs/vdb/error/metadata/ENOSPC/retry_timeout_seconds
-1
-1

[root@master ~]# echo 60 > /sys/fs/xfs/vdb/error/metadata/EIO/retry_timeout_seconds; echo 60 > /sys/fs/xfs/vdb/error/metadata/ENOSPC/retry_timeout_seconds 
[root@master ~]# cat /sys/fs/xfs/vdb/error/metadata/EIO/retry_timeout_seconds /sys/fs/xfs/vdb/error/metadata/ENOSPC/retry_timeout_seconds
60
60
[root@master ~]# 
```

2023-04-12 14:42 UTC, harshavardhana commented on pkg/xfs/mount_linux.go
> +		return fmt.Errorf("unable to set EIO retry_timeout_seconds for device %v; %w", name, err)
These files are missing because kernel doesn't support until RHEL8 - we can't afford for DirectPV to throw errors on existing deployment.

2023-04-12 14:53 UTC, harshavardhana requested changes

2023-04-12 14:53 UTC, harshavardhana commented on pkg/xfs/mount_linux.go
> +		return fmt.Errorf("unable to set EIO retry_timeout_seconds for device %v; %w", name, err)
Also we need to set this to 1 for max_retries, we really don't want any retry via XFS beyond atleast 1 entry.

And perhaps we should reduce the retry only up-to 5s or worst 10s.

2023-04-13 02:08 UTC, balamurugana commented
Functional tests on rhel9 fails

2023-04-13 04:13 UTC, Praveenrajmani approved these changes

2023-04-13 04:29 UTC, Praveenrajmani approved these changes

2023-04-13 06:01 UTC, harshavardhana approved these changes

2023-04-13 06:01 UTC, merged